### ISSUE TITLE
Released idsueyesrc doesn't work

### ISSUE THREAD

**Issue by pdeman** [joshdoe/gst-plugins-vision#11]
Hi,
I  am trying to stream the video flux from an ids camera on rtp protocol. I am working on windows 10.
I installed gstreamer: (gst-launch-1.0)

> gst-launch-1.0 --version
> gst-launch-1.0 version 1.16.2
> GStreamer 1.16.2
> Unknown package origin

I downloaded the release of your gst-plugins-vision:
gst-plugins-vision-1.5.92-x86_64.zip
did:
`set GST_PLUGIN_PATH="G:\gstreamer\lib"`
(this is the extracted folder from the zip file)
and when I do:
`gst-launch-1.0 -v idsueyesrc ! x264enc ! rtph264pay ! udpsink host=127.0.0.2 port=5000`

> WARNING: erroneous pipeline: no element "idsueyesrc"

did I do something wrong ?
it seems that it can't find your dlls ?
![IDS](https://user-images.githubusercontent.com/16150529/76739917-47af7a00-676d-11ea-983f-211323bd7b06.png)

**Comment by 5shekel** [comment]
what do you get with 
`gst-inspect-1.0 -b`
this should show if something is not detected

**Comment by pdeman** [comment]
I get this:
gst-inspect-1.0.exe -b
Blacklisted files:

Total count: 0 blacklisted files

**Comment by pdeman** [comment]
here is the result of gst-device-monitor:
gst-device-monitor-1.0.exe
Probing devices...


Device found:

        name  : 2370 (NVIDIA High Definition Audio)
        class : Audio/Sink
        caps  : audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 2 ];
                audio/x-raw, format=(string)U8, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 2 ];
                audio/x-ac3, framed=(boolean)true;
                audio/x-dts, framed=(boolean)true;
        properties:
                device.api = directsound
                device.guid = "\{A4430BAF-C95F-4975-93FF-9283B0AA77C2\}"
                directsound.device.driver = "\{0.0.0.00000000\}.\{a4430baf-c95f-4975-93ff-9283b0aa77c2\}"
                directsound.device.description = "2370\ \(NVIDIA\ High\ Definition\ Audio\)"
        gst-launch-1.0 ... ! directsoundsink device="\{A4430BAF-C95F-4975-93FF-9283B0AA77C2\}"


Device found:

        name  : Digital Audio (S/PDIF) (High Definition Audio Device)
        class : Audio/Sink
        caps  : audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 2 ];
                audio/x-raw, format=(string)U8, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 2 ];
                audio/x-ac3, framed=(boolean)true;
                audio/x-dts, framed=(boolean)true;
        properties:
                device.api = directsound
                device.guid = "\{4BD63301-3EB0-47F0-882B-624191167E86\}"
                directsound.device.driver = "\{0.0.0.00000000\}.\{4bd63301-3eb0-47f0-882b-624191167e86\}"
                directsound.device.description = "Digital\ Audio\ \(S/PDIF\)\ \(High\ Definition\ Audio\ Device\)"
        gst-launch-1.0 ... ! directsoundsink device="\{4BD63301-3EB0-47F0-882B-624191167E86\}"


Device found:

        name  : Headphones (High Definition Audio Device)
        class : Audio/Sink
        caps  : audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 2 ];
                audio/x-raw, format=(string)U8, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 2 ];
                audio/x-ac3, framed=(boolean)true;
                audio/x-dts, framed=(boolean)true;
        properties:
                device.api = directsound
                device.guid = "\{F893BAC9-248F-4A97-A543-76735D316726\}"
                directsound.device.driver = "\{0.0.0.00000000\}.\{f893bac9-248f-4a97-a543-76735d316726\}"
                directsound.device.description = "Headphones\ \(High\ Definition\ Audio\ Device\)"
        gst-launch-1.0 ... ! directsoundsink device="\{F893BAC9-248F-4A97-A543-76735D316726\}"


Device found:

        name  : Primary Sound Driver
        class : Audio/Sink
        caps  : audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 2 ];
                audio/x-raw, format=(string)U8, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 2 ];
                audio/x-ac3, framed=(boolean)true;
                audio/x-dts, framed=(boolean)true;
        properties:
                device.api = directsound
                device.guid = "\(NULL\)"
                directsound.device.driver = ""
                directsound.device.description = "Primary\ Sound\ Driver"
        gst-launch-1.0 ... ! directsoundsink


Device found:

        name  : Primary Sound Capture Driver
        class : Audio/Source
        caps  : audio/x-raw, format=(string){ S16LE, S8 }, layout=(string)interleaved, rate=(int)[ 1, 2147483647 ], channels=(int)[ 1, 2 ];
        properties:
                device.api = directsound
                device.guid = "\(NULL\)"
                directsound.device.driver = ""
                directsound.device.description = "Primary\ Sound\ Capture\ Driver"
        gst-launch-1.0 directsoundsrc ! ...


Device found:

        name  : Headphones (High Definition Audio Device)
        class : Audio/Sink
        caps  : audio/x-raw, format=(string)F32LE, layout=(string)interleaved, rate=(int)44100, channels=(int)2, channel-mask=(bitmask)0x0000000000000003;
        properties:
                device.api = wasapi
                device.strid = "\{0.0.0.00000000\}.\{f893bac9-248f-4a97-a543-76735d316726\}"
                wasapi.device.description = "Headphones\ \(High\ Definition\ Audio\ Device\)"
        gst-launch-1.0 ... ! wasapisink device="\{0.0.0.00000000\}.\{f893bac9-248f-4a97-a543-76735d316726\}"


Device found:

        name  : 2370 (NVIDIA High Definition Audio)
        class : Audio/Sink
        caps  : audio/x-raw, format=(string)F32LE, layout=(string)interleaved, rate=(int)48000, channels=(int)2, channel-mask=(bitmask)0x0000000000000003;
        properties:
                device.api = wasapi
                device.strid = "\{0.0.0.00000000\}.\{a4430baf-c95f-4975-93ff-9283b0aa77c2\}"
                wasapi.device.description = "2370\ \(NVIDIA\ High\ Definition\ Audio\)"
        gst-launch-1.0 ... ! wasapisink device="\{0.0.0.00000000\}.\{a4430baf-c95f-4975-93ff-9283b0aa77c2\}"


Device found:

        name  : Digital Audio (S/PDIF) (High Definition Audio Device)
        class : Audio/Sink
        caps  : audio/x-raw, format=(string)F32LE, layout=(string)interleaved, rate=(int)44100, channels=(int)2, channel-mask=(bitmask)0x0000000000000003;
        properties:
                device.api = wasapi
                device.strid = "\{0.0.0.00000000\}.\{4bd63301-3eb0-47f0-882b-624191167e86\}"
                wasapi.device.description = "Digital\ Audio\ \(S/PDIF\)\ \(High\ Definition\ Audio\ Device\)"
        gst-launch-1.0 ... ! wasapisink device="\{0.0.0.00000000\}.\{4bd63301-3eb0-47f0-882b-624191167e86\}"

it doesn't see the ids.

**Comment by pdeman** [comment]
do I need to do anything with my camera ? or once is detected by the usb port it's ok?

**Comment by 5shekel** [comment]
its ok
what does this show in powershell
```$env:GST_PLUGIN_PATH```
and
```gst-inspect-1.0.exe  | Select-String -Pattern ids```

**Comment by 5shekel** [comment]
i can share this tested `libgstidsueye.dll` with you
it is my own compiled windows dll. 
```
gst-inspect-1.0.exe  | Select-String -Pattern ids
idsueye:  idsueyesrc: IDS uEye Video Source
```
https://mega.nz/#!EFYjQK7C!QTBBtUXSEXeoxXxd2NHuf5Yve3e1U2T_QrnE6BMWE8c

**Comment by pdeman** [comment]
G:\> $env:GST_PLUGIN_PATH
G:\gstreamer\lib

and here is the folder "tree":

    Directory: G:\gstreamer\lib\gstreamer-1.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
------       10/10/2019     13:52          38912 libgstaptina.dll
------       10/10/2019     13:52          44544 libgstbitflow.dll
------       10/10/2019     13:52          44544 libgstedt.dll
------       10/10/2019     13:52          45056 libgsteuresys.dll
------       10/10/2019     13:52          39936 libgstextractcolor.dll
------       10/10/2019     13:52          86016 libgstgenicam.dll
------       10/10/2019     13:52          39424 libgstgigesim.dll
------       10/10/2019     13:52          45568 libgstidsueye.dll
------       10/10/2019     13:52          46080 libgstimperxflex.dll
------       10/10/2019     13:52          46080 libgstimperxsdi.dll
------       10/10/2019     13:52          57856 libgstkaya.dll
------       10/10/2019     13:52          45568 libgstmatrox.dll
------       10/10/2019     13:52          40448 libgstmisb.dll
------       10/10/2019     13:52          47616 libgstniimaq.dll
------       10/10/2019     13:52          56832 libgstniimaqdx.dll
------       10/10/2019     13:52          44544 libgstphoenix.dll
------       10/10/2019     13:52          48640 libgstpixci.dll
------       10/10/2019     13:52          86016 libgstpleora.dll
------       10/10/2019     13:52          92160 libgstsapera.dll
------       10/10/2019     13:52          29184 libgstselect.dll
------       10/10/2019     13:52          50176 libgstvideoadjust.dll

and for the inspect:
 .\gst-inspect-1.0.exe | Select-String -Pattern ids

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.447: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstaptina.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstaptina.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.467: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstbitflow.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstbitflow.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.508: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstedt.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstedt.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.529: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgsteuresys.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgsteuresys.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.554: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstextractcolor.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstextractcolor.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.576: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstgenicam.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstgenicam.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.597: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstgigesim.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstgigesim.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.619: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstidsueye.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstidsueye.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.640: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstimperxflex.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstimperxflex.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.665: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstimperxsdi.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstimperxsdi.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.688: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstkaya.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstkaya.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.708: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstmatrox.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstmatrox.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.730: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstmisb.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstmisb.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.757: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstniimaq.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstniimaq.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.779: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstniimaqdx.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstniimaqdx.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.812: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstphoenix.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstphoenix.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.834: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstpixci.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstpixci.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.856: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstpleora.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstpleora.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.878: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstsapera.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstsapera.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.899: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstselect.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstselect.dll': The specified module could not be found.

(gst-inspect-1.0:2552): GStreamer-WARNING **: 12:41:05.922: Failed to load plugin 'G:\gstreamer\lib\gstreamer-1.0\libgstvideoadjust.dll': 'G:\gstreamer\lib\gstreamer-1.0\libgstvideoadjust.dll': The specified module could not be found.

using powershell there is a problem

**Comment by 5shekel** [comment]
yes i get the same when trying to run gst-plugins-vision-1.5.92-x86_64.zip release DLLs.   
they might be broken for gstreamer-1.6  idk

**Comment by 5shekel** [comment]
try to build yourself using visual studio and cmake on windows , its ~fun!

**Comment by pdeman** [comment]
it seems to work using your dll:
 .\gst-inspect-1.0.exe | Select-String -Pattern ids

idsueye:  idsueyesrc: IDS uEye Video Source

**Comment by pdeman** [comment]
I don't have "all set LIBXML2_DIR=%GSTREAMER_DIR%
set LIBICONV_DIR=%GSTREAMER_DIR%
set GLIB2_DIR=%GSTREAMER_DIR%
set NIIMAQ_DIR=C:\Program Files\National Instruments
set EURESYS_DIR=C:\Program Files\Euresys\MultiCam
set OpenCV_DIR=C:\Users\joshua.doe\Apps\opencv" this and not sure I want it

**Comment by 5shekel** [comment]
you dont require any one of those.   
these is if you try to build for all cameras.

**Comment by 5shekel** [comment]
the `opencv` one is for other plugins included.   
also not necessary.

**Comment by joshdoe** [comment]
I usually see that error when there is a missing dependency, which is usually the camera/framegrabber runtime DLLs. I believe I built the uploaded binaries against uEye 4.61, perhaps @5shekel built against a different version that you happen to be running and there's a version incompatibility. Checking with Dependency Walker, my binaries are dependent on `ueye_api64.dll`, which the uEye installer placed in `C:\windows\system32`. Perhaps your `PATH` was changed to exclude that directory. I'd suggest trying out [Dependency Walker](http://www.dependencywalker.com/).

**Comment by pdeman** [comment]
ok I tried to do the cmake
and even with the 
set GSTREAMER_DIR="G:\gstreamer"
I have got this:
![cmakeerror](https://user-images.githubusercontent.com/16150529/76756909-ec8a8100-6786-11ea-84ef-ecb3e6eaf8b2.png)

**Comment by 5shekel** [comment]
your machine cant find gstreamer  
see https://gstreamer.freedesktop.org/documentation/installing/on-windows.html

> It is the application's responsibility to ensure that, at runtime, GStreamer can access its libraries and plugins. It can be done by adding %GSTREAMER_ROOT_X86%\bin to the PATH environment variable

**Comment by 5shekel** [comment]
i recommend rapidEE for windows path stuff
![image](https://user-images.githubusercontent.com/222526/76757254-f5cc1b80-678f-11ea-904f-9447e13306a8.png)

**Comment by pdeman** [comment]
it is in the path already:
![2020-03-16 13_09_06-Environment Variables](https://user-images.githubusercontent.com/16150529/76757303-a71a8380-6787-11ea-93f7-ab75ad5af0ca.png)

**Comment by pdeman** [comment]
I have an error using your dll (not succeed to compile myself for now) :

> WARNING: erroneous pipeline: could not link idsueyesrc0 to x264enc0

**Comment by 5shekel** [comment]
show complete pipeline. 
start with a simple display
```gst-launch-1.0.exe -v idsueyesrc ! videoconvert ! fpsdisplaysink```

**Comment by pdeman** [comment]
I tried to built it using visual sutio or cmake but without succes so I am using the dll you sent me.
` gst-launch-1.0.exe -v idsueyesrc ! videoconvert ! fpsdisplaysink`

> Setting pipeline to PAUSED ...
> ERROR: Pipeline doesn't want to pause.
> /GstPipeline:pipeline0/GstFPSDisplaySink:fpsdisplaysink0/GstAutoVideoSink:fps-display-video_sink/GstD3DVideoSink:fps-display-video_sink-actual-sink-d3dvideo: sync = true
> ERROR: from element /GstPipeline:pipeline0/GstIdsueyeSrc:idsueyesrc0: Failed to load parameters from EEPROM
> Additional debug info:
> C:\dev\gst-plugins-vision\sys\idsueye\gstidsueyesrc.c(487): gst_idsueyesrc_start (): /GstPipeline:pipeline0/GstIdsueyeSrc:idsueyesrc0
> Setting pipeline to NULL ...
> Freeing pipeline ...
>

**Comment by 5shekel** [comment]
regarding your cmake, did you install both runtime and devel packages? 
```
https://gstreamer.freedesktop.org/data/pkg/windows/1.6.4/gstreamer-1.0-devel-x86_64-1.6.4.msi
https://gstreamer.freedesktop.org/data/pkg/windows/1.6.4/gstreamer-1.0-x86_64-1.6.4.msi
```

**Comment by 5shekel** [comment]
you have to first open ids in its demo software and `file>save>parameter set`  
 it says there in line 4. 
` Failed to load parameters from EEPROM`

**Comment by pdeman** [comment]
gst-launch-1.0.exe -v idsueyesrc ! videoconvert ! fpsdisplaysink ! config-file : G:\gstreamer\test.ini
WARNING: erroneous pipeline: no element "config-file"

**Comment by 5shekel** [comment]
`gst-launch-1.0.exe -v idsueyesrc config-file="G:\gstreamer\test.ini" ! videoconvert ! fpsdisplaysink`

**Comment by pdeman** [comment]
yes I just found that. but I still get stuck to send h264 video through rtp

**Comment by 5shekel** [comment]
you first have to encode the stream before you send it. 
try  
```
gst-launch-1.0.exe -v idsueyesrc ! videoconvert ! queue ! x264enc ! rtph264pay ! udpsink host=127.0.0.2 port=5000
```
videoconvert and queue will try to adjust and buffer your pipeline to fit. use them generously. 
```

**Comment by pdeman** [comment]
thanks a lot. 
the "host" is the ip address of the computer that I want to "receive" the streaming ?

**Comment by 5shekel** [comment]
yep

**Comment by 5shekel** [comment]
> I usually see that error when there is a missing dependency, which is usually the camera/framegrabber runtime DLLs. I believe I built the uploaded binaries against uEye 4.61, perhaps @5shekel built against a different version that you happen to be running and there's a version incompatibility. Checking with Dependency Walker, my binaries are dependent on `ueye_api64.dll`, which the uEye installer placed in `C:\windows\system32`. Perhaps your `PATH` was changed to exclude that directory. I'd suggest trying out [Dependency Walker](http://www.dependencywalker.com/).

i couldnt get depwalker to run here.   
found on github [Dependencies](https://github.com/lucasg/Dependencies) that did.  
and yes. im missing a few
![image](https://user-images.githubusercontent.com/222526/76761668-86a6f500-6798-11ea-8c8c-73331a0d5fc8.png)

**Comment by joshdoe** [comment]
Let's try and focus this issue a bit, it seems you're trying to do three different things, 1) use my released binaries, 2) use 5shekel's binary, 3) compile from source. It seems like you were having success in grabbing frames using 5shekel's binary, which likely matches your version of uEye compared to mine.

1. What version of uEye are you running?
2. Have you successfully been able to show live video from the camera using any binary?

**Comment by pdeman** [comment]
Hi,

> Have you successfully been able to show live video from the camera using any binary?
yes using 5shekel's binary.

> What version of uEye are you running?
![2020-03-17 13_06_21-IDS Camera Manager - 64-Bit](https://user-images.githubusercontent.com/16150529/76855017-879b5d80-6850-11ea-9a65-8a095352cf68.png)
![2020-03-17 13_07_29-Informations générales](https://user-images.githubusercontent.com/16150529/76855018-8833f400-6850-11ea-9d07-71b883a8a6cb.png)

now my problem is to understand why I can't compile from source, which is what I was trying at first.

**Comment by joshdoe** [comment]
I see you mentioned `GSTREAMER_DIR`, it should be `GSTREAMER_ROOT=C:/gstreamer/1.0/x86_64`, or wherever you have it installed.

**Comment by joshdoe** [comment]
@pdeman, I've updated the [README](https://github.com/joshdoe/gst-plugins-vision/blob/master/README.md) to include a section on compilation. Read that and give me any feedback you can.

**Comment by 5shekel** [comment]
this is my log, following readme.  
but replaced with visual studio 2019.   
`cmake -G "Visual Studio 16 2019" -A x64 -Wno-dev ..`

``` Cmake

-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find BITFLOW (missing: BITFLOW_INCLUDE_DIR BITFLOW_LIBRARIES) 
-- Could NOT find NIIMAQ (missing: NIIMAQ_INCLUDE_DIR NIIMAQ_LIBRARIES) 
-- Could NOT find NIIMAQDX (missing: NIIMAQDX_INCLUDE_DIR NIIMAQDX_LIBRARIES) 
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: OFF
-- Found OpenCV 4.1.1 in C:/tools/opencv/build/x64/vc15/lib
-- You might need to add C:\tools\opencv\build\x64\vc15\bin to your PATH to be able to run your applications.
-- Could NOT find APTINA (missing: APTINA_INCLUDE_DIR APTINA_LIBRARIES) 
-- Could NOT find EDT (missing: EDT_INCLUDE_DIR EDT_LIBRARIES) 
-- Could NOT find EURESYS (missing: EURESYS_INCLUDE_DIR EURESYS_LIBRARIES)
-- Could NOT find GIGESIM (missing: GIGESIM_INCLUDE_DIR GIGESIM_LIBRARIES) 
-- Could NOT find IMPERX_FLEX (missing: IMPERX_FLEX_INCLUDE_DIR IMPERX_FLEX_LIBRARIES) 
-- Could NOT find IMPERX_SDI (missing: IMPERX_SDI_INCLUDE_DIR IMPERX_SDI_LIBRARIES) 
-- IOTECHDAQX: WARNING: include dir not found
-- IOTECHDAQX: WARNING: library not found
-- Could NOT find IOTECHDAQX (missing: IOTECHDAQX_INCLUDE_DIR IOTECHDAQX_LIBRARIES)
-- Could NOT find KAYA (missing: KAYA_INCLUDE_DIR KAYA_LIBRARIES) 
-- Could NOT find MATROX (missing: MATROX_INCLUDE_DIR MATROX_LIBRARIES) 
CMake Warning at cmake/modules/FindPhoenix.cmake:12 (message):
  PHOENIX: WARNING: PHOENIX_DIR not set, set to dir SDKX.XX where X.XX is the
  version
Call Stack (most recent call first):
  CMakeLists.txt:97 (find_package)


CMake Warning at cmake/modules/FindPhoenix.cmake:33 (message):
  PHOENIX: WARNING: not found, make sure PHOENIX_DIR is set to dir SDKX.XX
Call Stack (most recent call first):
  CMakeLists.txt:97 (find_package)


-- Could NOT find PHOENIX (missing: PHOENIX_INCLUDE_DIR PHOENIX_LIBRARIES)
CMake Error at cmake/modules/FindPleora.cmake:43 (file):
  file STRINGS file "C:/dev/gsp/Pleora_INCLUDE_DIR-NOTFOUND/PvVersion.h"
  cannot be read.
Call Stack (most recent call first):
  CMakeLists.txt:100 (find_package)


-- Could NOT find Pleora (missing: Pleora_INCLUDE_DIR Pleora_LIBRARY_DIR Pleora_LIBRARIES)
-- Could NOT find SAPERA (missing: SAPERA_INCLUDE_DIR SAPERA_LIBRARIES) 
-- XCLIB: WARNING: include dir not found
-- XCLIB: WARNING: library not found
-- Could NOT find XCLIB (missing: XCLIB_INCLUDE_DIR XCLIB_LIBRARIES)

-----------------------------------------------------------------------------
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
-----------------------------------------------------------------------------
   * GStreamer - Required to build gst-plugins-vision
   * GStreamer base library - Required to build most plugins
   * GStreamer video library - Required to build several video plugins
   * GLib - Required to build gst-plugins-vision
   * GObject - Required to build gst-plugins-vision
   * Orc - Required library to improve performance
   * OpenCV - Required to build sensorfx plugin
   * IDS uEye - Required to build IDS uEye source element

-----------------------------------------------------------------------------
-- The following OPTIONAL packages could NOT be located on your system.
-- Consider installing them to enable more features from this software.
-----------------------------------------------------------------------------
   * BitFlow  <http://www.bitflow.com/>
     Required to build BitFlow source element
   * NI-IMAQ  <http://www.ni.com/>
     Required to build National Instruments IMAQ source element
   * NI-IMAQdx  <http://www.ni.com/>
     Required to build National Instruments IMAQdx source element
   * FreeImage  <http://freeimage.sourceforge.net/>
     Required to build FreeImage plugin
   * Aptina  <http://www.onsemi.com/>
     Required to build aptinasrc source element
   * EDT  <http://www.edt.com/>
     Required to build EDT PDV source element
   * Euresys  <http://www.euresys.com/>
     Required to build Euresys source element
   * GigESim  <http://www.ab-soft.com/>
     Required to build A&B Soft GigESim sink element
   * Imperx FrameLink Express  <http://www.imperx.com/>
     Required to build Imperx FrameLink Express source element
   * Imperx HD-SDI Express  <http://www.imperx.com/>
     Required to build Imperx HD-SDI Express source element
   * IOtech DaqX  <http://www.mccdaq.com/>
     Required to build IOtech DaqX source element
   * KAYA Vision Point  <http://www.kayainstruments.com/>
     Required to build KAYA source element
   * Matrox MIL  <http://www.matrox.com/imaging/>
     Required to build Matrox MIL source element
   * Active Silicon Phoenix  <http://www.activesilicon.com/>
     Required to build Active Silicon Phoenix source element
   * Pleora eBUS  <http://www.pleora.com/>
     Required to build Pleora eBUS source element
   * Teledyne DALSA Sapera  <http://www.teledynedalsa.com/>
     Required to build Teledyne DALSA Sapera source element
   * EPIX PIXCI  <http://www.epixinc.com/>
     Required to build EPIX PIXCI source element

-----------------------------------------------------------------------------

-- Configuring incomplete, errors occurred!
See also "C:/dev/gsp/build/CMakeFiles/CMakeOutput.log".
```

**Comment by joshdoe** [comment]
@pdeman Is this issue still valid? Regarding the last comment by @5shekel, those errors should be resolved now.

**Comment by pdeman** [comment]
Hi, i still didn't have compiled the sources. Using @5shekel libs it worked. I don't have access to the camera for now ...

**Comment by joshdoe** [comment]
I'll close this for now then.

**Comment by pdeman** [comment]
How can i check that: gst-launch-1.0.exe -v idsueyesrc ! videoconvert ! queue ! x264enc ! rtph264pay ! udpsink host=127.0.0.2 port=5000 is working ? I can't find out how to connect vlc to it to verify that

**Comment by joshdoe** [comment]
Stream video from GStreamer:
`gst-launch-1.0.exe videotestsrc ! queue ! videoconvert ! x264enc ! rtph264pay ! udpsink host=127.0.0.1 port=5000`

Receive video via GStreamer:
` gst-launch-1.0.exe udpsrc port=5000 ! "application/x-rtp,media=(string)video,clock-rate=(int)90000,encoding-name=(string)H264,payload=(int)96" ! queue ! rtph264depay ! decodebin ! videoconvert ! autovideosink`

@pdeman, to open the stream in VLC you need an SDP file, [as described here](https://developer.ridgerun.com/wiki/index.php/Introduction_to_network_streaming_using_GStreamer#Generating_a_SDP_file_from_a_streaming_pipeline). 

To open in OpenCV, I believe you can provide the same SDP file via VideoReader, or you can build OpenCV with GStreamer support, then you just provide a gst-launch style string to VideoReader, as seen [here on StackOverflow](https://answers.opencv.org/question/202017/how-to-use-gstreamer-pipeline-in-opencv/).
