### ISSUE TITLE
GST_BUFFER_TIMESTAMP is 0.10 

### ISSUE THREAD

**Issue by 5shekel** [joshdoe/gst-plugins-vision#12]
i see this all around  
but it looks like gstreamer 1.0 handles it gracefully into `GST_BUFFER_PTS`.

> GST_BUFFER_TIMESTAMP is gone, use GST_BUFFER_PTS or GST_BUFFER_DTS instead. 

https://github.com/joshdoe/gst-plugins-vision/blob/7292eaf3539a0783b1b3f33ea54bce3e4bd78607/sys/imperxflex/gstframelinksrc.c#L701

**Comment by joshdoe** [comment]
I just reviewed the gstreamer and gst-plugins-good projects, and `GST_BUFFER_TIMESTAMP` is used pretty extensively. Given the [preprocessor define here](https://github.com/GStreamer/gstreamer/blob/cc55b304ef4ab1cd95f6348d33f268ccebaab8e8/gst/gstcompat.h#L44), and that the core devs didn't seem bothered to switch over to `GST_BUFFER_PTS` when they ported everything to 1.0, I probably will leave this alone. However, if you wish to make such modifications and provide a merge request, I'll be happy to accept it.
