### ISSUE TITLE
Problems trying to compile on Ubuntu 16.04 for ARM64

### ISSUE THREAD

**Issue by harendracmaps** [joshdoe/gst-plugins-vision#15]
I want to compile the basler camera plugin for arm64. Is it possible to compile only that module? I tried compiling thw whole but it is throwing issue for Orc which is not availbe for arm as of now. 

Please assist me compiling for arm64.

**Comment by 5shekel** [comment]
please close as you found it  #2 
`sudo apt search liborc`
