### ISSUE TITLE
install location CMAKE_INSTALL_PREFIX instead of hardcode

### ISSUE THREAD

**Issue by 5shekel** [joshdoe/gst-plugins-vision#20]
i prefer to control where plugins go. 
but to not break scripts out there   
`CMAKE_INSTALL_PREFIX` lib/gstreamer-1.0 by default
and `GST_PLUGIN_PATH` updated, an extra step
```
install(TARGETS ${libname}
-  LIBRARY DESTINATION lib/gstreamer-1.0)
+ LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX})
``

**Comment by 5shekel** [comment]
LIBRARY DESTINATION can probably be overridden without any change

**Comment by joshdoe** [comment]
Sounds good, one thing though, I currently have a library klv that needs to go into a bin directory, how to handle that? Currently `CMAKE_INSTALL_PREFIX` would be something like `/opt/gst-plugins-vision`, then there'd be a `bin` and `lib/gstreamer-1.0` directory. I could ignore `CMAKE_INSTALL_PREFIX` entirely and use `PLUGIN_INSTALL_PATH` and `LIBRARY_INSTALL_PATH` or similar. Note that I should make the klv library optional, but still, I might have other libraries in the future and would need to handle those.

**Comment by 5shekel** [comment]
if klv needs to go to bin maybe have different logic as its not "acting" as a regular lib
i would keep default CMAKE_INSTALL_PREFIX  as before lib/gstreamer-1.0 this might be easier and not break expectations

**Comment by joshdoe** [comment]
Sorry I meant to say the supporting library libgstklv-1.0 goes in lib like
libgstvideo-1.0, the plugin libgstklv goes in lib/gstreamer-1.0.

**Comment by joshdoe** [comment]
Check the latest [commit](https://github.com/joshdoe/gst-plugins-vision/commit/323ef8df322ccbce8818701f0e21c63dfae21b8b) on the linux branch which introduces better defaults, and options to override plugin installation directory with `PLUGIN_INSTALL_DIR`.

**Comment by 5shekel** [comment]
noticed klv 
requires  the following if not in the default `LD_LIBRARY_PATH` search path
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"location of libgstklv-1.0-0.so"`

```
ldd /opt/gst/plugins/gstreamer-1.0/libgstklv.so 
        linux-vdso.so.1 (0x0000007fa66c4000)
        libglib-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0 (0x0000007fa6553000)
        libgobject-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgobject-2.0.so.0 (0x0000007fa64f5000)
        libgstreamer-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstreamer-1.0.so.0 (0x0000007fa63c5000)
        libgstbase-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstbase-1.0.so.0 (0x0000007fa634e000)
        libgstklv-1.0-0.so => not found
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007fa61f5000)
        /lib/ld-linux-aarch64.so.1 (0x0000007fa6699000)
        libpcre.so.3 => /lib/aarch64-linux-gnu/libpcre.so.3 (0x0000007fa6183000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007fa6157000)
        libffi.so.6 => /usr/lib/aarch64-linux-gnu/libffi.so.6 (0x0000007fa613f000)
        libgmodule-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgmodule-2.0.so.0 (0x0000007fa612b000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007fa6071000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007fa605c000)
```

**Comment by joshdoe** [comment]
Yep, is that unexpected? The klv and pleora plugins currently depend on that library. I should make klv optional for pleora.

**Comment by 5shekel** [comment]
expected, if not in default location
should update the readme for this
or maybe a nice warning during install

**Comment by joshdoe** [comment]
@5shekel On the linux branch I've made KLV support optional with `ENABLE_KLV`, and updated the [README](https://github.com/joshdoe/gst-plugins-vision/blob/linux/README.md) quite a bit with instructions for Linux, including mentioning how to disable KLV or to set the library search path.

Think these can close out the issue? I'll then merge the branch with master.

**Comment by joshdoe** [comment]
@5shekel I'm realizing these changes broke packaging. For CPack to work, it's expecting a relative path, not an absolute path for the `install()` directives like I did in commit 26e05b705. I've changed this locally so by default:
```
set(LIBRARY_INSTALL_DIR "bin")
set(PLUGIN_INSTALL_DIR "lib/gstreamer-1.0/")
set(PDB_INSTALL_DIR "lib/gstreamer-1.0/")
```

This works for Windows, for both packaging and installing. Think this suffices for Linux as well (minus PDB of course). You can always override and specify an absolute path for these variables, that will just break packaging for that build.
