### ISSUE TITLE
freeimage: port to GStreamer 1.0

### ISSUE THREAD

**Issue by 5shekel** [joshdoe/gst-plugins-vision#23]
multiple 0.10 calls
```
GST_FLOW_UNEXPECTED -> GST_FLOW_EOS
GST_FLOW_WRONG_STATE -> GST_FLOW_FLUSHING
```
see [porting guide](https://github.com/ApsOps/GStreamer-0.10-to-1.0-porting-guide/blob/master/porting-to-1.0.md)

and errors on `config.h` 
i suspect something to do with 
`add_definitions(-DHAVE_CONFIG_H)` in its CMakeLists.txt

also plugin_define had issues
```
GST_PLUGIN_DEFINE (GST_VERSION_MAJOR,
    GST_VERSION_MINOR,
    freeimage,
    "FreeImage plugin library", plugin_init, GST_PACKAGE_VERSION, GST_PACKAGE_LICENSE, GST_PACKAGE_NAME,
    GST_PACKAGE_ORIGIN)
```

**Comment by joshdoe** [comment]
I haven't used freeimage in some time, so I suppose I never bothered porting it to 1.0. Do you plan to use it? I suppose it probably still supports a few image formats not supported by other GStreamer plugins.

**Comment by 5shekel** [comment]
i have no use for it ATM, it just blocked the rest of the build
