### ISSUE TITLE
update gst-launch example to 1.0

### ISSUE THREAD

**Issue by 5shekel** [joshdoe/gst-plugins-vision#26]
effects many
```
-gst-launch -v videotestsrc ! autovideoconvert ! gigesimsink
+gst-launch-1.0 -v videotestsrc ! autovideoconvert ! gigesimsink
```

**Comment by joshdoe** [comment]
You're suggesting this for the comment header in the source files? Looking in GStreamer packages, not every source file has an example line. Honestly most examples are pretty uninformative, I'd almost just as rather get rid of them entirely unless the use is non intuitive. I'd take a PR though.
