### ISSUE TITLE
Yocto/Bitbake cross compiling

### ISSUE THREAD

**Issue by chiuwe** [joshdoe/gst-plugins-vision#34]
Does anyone know how to cross compiling these plugins with yocto/bitbake recipes?
I am using the original gst-pylon repo but i get an error saying
"checking for /opt/pylon5/include/pylonc... configure: error: cannot check for file existence when cross compiling"
I guess its telling me that I can't cross compile? Though i feel like i should be able to still.
I just dont know how to include pylon5 src into the recipe.

**Comment by willingtonvr** [comment]
Look close to cmake/modules/FindPylon.cmake
it looks for lib64 folder
tested with pylon 6 and works, just symlink lib64 to lib on /opt/pylon

**Comment by chiuwe** [comment]
"tested with pylon 6" as in you have a recipe for building this in bitbake?

I have lib64 folder with pylon 5. Maybe my real problem is i dont know how to properly install pylon with bitbake recipe.
so I can't have it be a dependency of gst-plugin.

If you're using the yocto environment how do you install pylon?

**Comment by willingtonvr** [comment]
I just install de the deb package, after that i got mostly of the pylon on /opt/pylon, the udev on /etc and shortcuts to /usr/share
this post even pretty old could be used to create the bitbake recipe.

https://stackoverflow.com/questions/18382407/cmake-with-bitbake-recipe
