### ISSUE TITLE
Pylonsrc Image Resized 

### ISSUE THREAD

**Issue by frankSDeviation** [joshdoe/gst-plugins-vision#37]
Hello,

My name is Frank and I want to say that you have done awesome work! I am coming over from Zingmars' git. I was having issues with the corrupted frames bug but your code has fixed that for me. My current project requires me to send a video stream of my two Basler cameras over UDP with zero latency. I am able to do this to some degree. My video stream works just fine but crashes after some time. I dont have to stream the image at full resolution (1600x1200). I can change it to something smaller like 800x600, but when I do that the image sort of displays an area of interest instead of resizing the entire image. This is the pipeline I am using to send the video stream over UDP:

gst-launch-1.0 -v pylonsrc pixel-format=mono8 width=1600 height=1200 camera=0 ! "video/x-raw,format=GRAY8" ! videoflip method=vertical-flip ! videoconvert ! x264enc bitrate=30000 speed-preset=superfast qp-min=30 tune=zerolatency ! rtph264pay ! udpsink host=XXX.XXX.XXX port=XXXX

This is the error message I get when using the above pipeline:

c:2982:gst_pylonsrc_create:<pylonsrc0> Failed capture count=10. Status=4, ErrorCode=-503315950
0:01:10.491583302  5741 0x55bc1b2a82d0 ERROR               pylonsrc gstpylonsrc.c:2986:gst_pylonsrc_create:<pylonsrc0> Error in the image processing loop. Status=4, ErrorCode=-503315950
ERROR: from element /GstPipeline:pipeline0/GstPylonSrc:pylonsrc0: Internal data stream error.
Additional debug info:
gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstPylonSrc:pylonsrc0:
streaming stopped, reason error (-5)
Execution ended after 0:01:10.000411637
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
0:01:10.493346976  5741 0x55bc1b273890 DEBUG               pylonsrc gstpylonsrc.c:3004:gst_pylonsrc_stop:<pylonsrc0> stop
0:01:10.540193224  5741 0x55bc1b273890 DEBUG               pylonsrc gstpylonsrc.c:3048:pylonc_disconnect_camera:<pylonsrc0> Camera disconnected.
Setting pipeline to NULL ...
Freeing pipeline ...
0:01:10.540830965  5741 0x55bc1b273890 DEBUG               pylonsrc gstpylonsrc.c:3015:gst_pylonsrc_dispose:<pylonsrc0> dispose
0:01:10.540859517  5741 0x55bc1b273890 DEBUG               pylonsrc gstpylonsrc.c:3023:gst_pylonsrc_finalize:<pylonsrc0> finalize

This works fine for about a minute or so but then crashes. I can get around this by reducing the image size to 800x600 but I get this image when I do that:

![image](https://user-images.githubusercontent.com/68567246/90918375-614a9280-e399-11ea-9144-13d4e4b8f739.png)

When I apply a 1600x1200 image size, this is what I get:

![image](https://user-images.githubusercontent.com/68567246/90919653-aff92c00-e39b-11ea-913d-ded4585e7f41.png)

Is there any way I can display the full image at 800x600? I would assume less bandwidth would be used if I send an 800x600 image instead of a 1600x1200. Also reducing the latency and bitrate is not an option at the moment. When I send the camera image with 800x600 over UDP, I have no problems and it does not crash. 

Thank you,
Frank

**Comment by ban1080** [comment]
You will have to choose the settings such that there is binning while maintaining a full ROI - https://docs.baslerweb.com/binning. in your case, it'd be 2 pixels horizontal binning, and 2 pixels vertical binning.

**Comment by frankSDeviation** [comment]
Thank you for the help ban1080!! that seems to have fixed my problem, well sort of. The image is now reduced to 800x600 but it looks like I have a pretty big loss in quality. Is there anyway to set the Q factor or increase the bitrate with the plugin? I have looked through the parameters using gst-inspect pylonsrc but I could not find anything. 

I also have another issue. So we are providing external sync to our two cameras. We have an application that we run that records the two cameras in sync with each other. We are also using one of the GPIO connectors on the back of the camera to provide sync to a set of LEDs that are being strobbed to provide lighting for both cameras. On our application this is not an issue and both cameras receive external sync and the LEDs turn on. But when I run Gstreamer, only one of the cameras appears to be getting my external sync. This picture more or less shows what I am trying to say:

![image](https://user-images.githubusercontent.com/68567246/91230617-ae539f00-e6e0-11ea-99ef-cd57180e0505.png)

As you can see only one of the cameras is completely lit. On our app both cameras work perfectly fine. Is there anyway I can set the cameras to receive external sync using the plugin?  The only parameter I saw that mentions a trigger is "continuous". Whenever I set this parameter to false, my pipeline does not run. 

I know this is hard to explain over a message board but if anyone is willing, I can give you a zoom demo so you may better understand what I am trying to do.

Thank you,
Frank

**Comment by frankSDeviation** [comment]
Hello everyone,

First I would like to say thank you so much for all of your help! I was finally able to do what I set out to do! I can now apply my external trigger to both my Basler cams I opened up the gstpylonsrc.c file and changed some of these lines of code:

static gboolean
gst_pylonsrc_set_trigger (GstPylonSrc * src)
{
  GENAPIC_RESULT res;

  // Set camera trigger mode
  const char *triggerSelectorValue = "FrameStart";
  _Bool isAvailAcquisitionStart =
      PylonDeviceFeatureIsAvailable (src->deviceHandle,
      "EnumEntry_TriggerSelector_AcquisitionStart");
  _Bool isAvailFrameStart = PylonDeviceFeatureIsAvailable (src->deviceHandle,
      "EnumEntry_TriggerSelector_FrameStart");
  const char *triggerMode = (src->continuousMode) ? "Off" : "On";

  GST_DEBUG_OBJECT (src, "Setting trigger mode.");

  // Check to see if the camera implements the acquisition start trigger mode only
  if (isAvailAcquisitionStart && !isAvailFrameStart) {
    // Select the software trigger as the trigger source
    res =
        PylonDeviceFeatureFromString (src->deviceHandle, "TriggerSelector",
        "FrameStart"); //AcquisitionStart
    PYLONC_CHECK_ERROR (src, res);
    res =
        PylonDeviceFeatureFromString (src->deviceHandle, "TriggerMode",
        triggerMode); 
    PYLONC_CHECK_ERROR (src, res);
    triggerSelectorValue = "AcquisitionStart";
  } else {
    // Camera may have the acquisition start trigger mode and the frame start trigger mode implemented.
    // In this case, the acquisition trigger mode must be switched off.
    if (isAvailAcquisitionStart) {
      res =
          PylonDeviceFeatureFromString (src->deviceHandle, "TriggerSelector",
          "FrameStart");//AcquisitionStart
      PYLONC_CHECK_ERROR (src, res);
      res =
          PylonDeviceFeatureFromString (src->deviceHandle, "TriggerMode",
          "On"); //"off"
      PYLONC_CHECK_ERROR (src, res);
    }
    // Disable frame burst start trigger if available
    if (PylonDeviceFeatureIsAvailable (src->deviceHandle,
            "EnumEntry_TriggerSelector_FrameBurstStart")) {
      res =
          PylonDeviceFeatureFromString (src->deviceHandle, "TriggerSelector",
          "FrameStart"); //FrameBurstStart
      PYLONC_CHECK_ERROR (src, res);
      res =
          PylonDeviceFeatureFromString (src->deviceHandle, "TriggerMode",
          "On"); //off
      PYLONC_CHECK_ERROR (src, res);
    }
    // To trigger each single frame by software or external hardware trigger: Enable the frame start trigger mode
    res =
        PylonDeviceFeatureFromString (src->deviceHandle, "TriggerSelector",
        "FrameStart");
    PYLONC_CHECK_ERROR (src, res);
    res =
        PylonDeviceFeatureFromString (src->deviceHandle, "TriggerMode",
        "On");//triggerMode
    PYLONC_CHECK_ERROR (src, res);
  }

After applying these changes I can now confirm that both my cameras are in sync.

![image](https://user-images.githubusercontent.com/68567246/91595235-10e2b000-e918-11ea-9ac0-0dee22e499d0.png)


Thank you,
Frank
