### ISSUE TITLE
[Question] Install pylonsrc plugin with pylon 6? 

### ISSUE THREAD

**Issue by mkaivs** [joshdoe/gst-plugins-vision#39]
Hi @joshdoe,

Thank for for create and maintain this list of plugin! I just want to ask if the `pylonsrc` plugin require pylon 5 or pylon 6 also work?

**Comment by joshdoe** [comment]
It's currently configured for Pylon 5, but it should probably work just fine with Pylon 6. Just edit the [FindPylon.cmake](https://github.com/joshdoe/gst-plugins-vision/blob/master/cmake/modules/FindPylon.cmake#L15) file to point to the right directory, or maybe even just set `PYLON_DIR` when configuring with CMake.

**Comment by mkaivs** [comment]
Hi @joshdoe,

Thank you for the quick reply! I will follow your advice and report back on the result.

**Comment by joshdoe** [comment]
@mkaivs ever try compiling for Pylon 6?

**Comment by mkaivs** [comment]
Hi @joshdoe,

Sorry for the delay, yes, it works fine with Pylon 6.
