### ISSUE TITLE
pylon installation

### ISSUE THREAD

**Issue by Drosaca** [joshdoe/gst-plugins-vision#45]
Hello,
I'm trying to add pylonsrc plugin but the zip files generated at the end are empty

![image](https://user-images.githubusercontent.com/36480154/99803035-057adb80-2b39-11eb-8bd8-bd7d868c2dde.png)
![image](https://user-images.githubusercontent.com/36480154/99803215-57bbfc80-2b39-11eb-8019-1fb26bd24ccb.png)

what did I do wrong ?

**Comment by Drosaca** [comment]
I fixed it
It's the first time I deal with gstreamer and I thought that there would be a file called pylonsrc inside the zip files
I also fixed the missing dependencies by adding pylon folder to LD_LIBRARY_PATH variable
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/pylon/lib`
now when I run 
`gst-launch-1.0 -v pylonsrc ! bayer2rgb ! videoconvert ! xvimagesink`
the output tells that there is No camera connected but there is I can see it using pylonviewer

**Comment by joshdoe** [comment]
The packaging still needs some work, but the ZIP file isn't truly needed, especially if you just want one plugin.

As far as the error, first thing is to increase the debug level, prepend your launch line with "GST_DEBUG=*:3,pylonsrc:9". You can export this to your environment instead if you'd like.
