### ISSUE TITLE
pixcisrc: Specific frame grabber SDKs

### ISSUE THREAD

**Issue by carlos-aguero** [joshdoe/gst-plugins-vision#5]
Hi,

We are trying to use your plugins with EPIX PIXCI-EB1 MINI-H its dependencies indicate that "Specific frame grabber SDKs" is required, to be more precise: XCLIB needs to be installed, there are difference XCLIB versions available at PIXCI:

1. XCLIB
2. XCLIBLITE
3. XCLIBIPL
4. XCAP-LITE

Could you please indicate if XCLIBLITE works with your plugins? Or XCLIB is required? It seems that we require to use pixcisrc element.

Regards,
Carlos A.

**Comment by joshdoe** [comment]
I only use the basic frame acquisition components of XCLIB, so I think just
the lite version will work, and without it in front of me I believe that's
what I used. Have you tried the Windows binary release I posted? It's in
need of an update but should work fine for your purposes. Looking forward
to getting your feedback.

**Comment by carlos-aguero** [comment]
Hi, thank you for your answer. Ok, will try with XCLIB-Lite version first.

We have not tried Windows binary release because we are not running Windows, our system is an NVIDIA Jetson TX1 running GStreamer 1.14.4 and Ubuntu 18.04.

Regards

**Comment by joshdoe** [comment]
I haven't used it on Linux, but I'd welcome any patches or a merge request to add support to this repository.

**Comment by carlos-aguero** [comment]
Hi,

Is there an specific requirement for having freeimage element at the project? Is it required at all or can it be removed? Seems that it is a GStreamer element for Gst-0.10 

Regards.

**Comment by joshdoe** [comment]
FreeImage was used for encoding and decoding various image formats, I haven't used it for years. Not needed for Epix support.

**Comment by joshdoe** [comment]
@carlos-aguero closing this unless you need further help.
