### ISSUE TITLE
Linux compiling error

### ISSUE THREAD

**Issue by TDKELL** [joshdoe/gst-plugins-vision#65]
When compiling the plugin I get the below error from the 'make' command:

`make[2]: *** No rule to make target '/usr/include/gstreamer-1.0/../../lib/z.lib', needed by 'sys/gentl/libgstgentl.so'. Stop.
CMakeFiles/Makefile2:447: recipe for target 'sys/gentl/CMakeFiles/gstgentl.dir/all' failed
make[1]: *** [sys/gentl/CMakeFiles/gstgentl.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
jetson@jetson:~/gst-plugins-vis`

I cannot work out what is causing this issue. Running Ubuntu ARM 18.04 LTS

**Comment by yair-mantis** [comment]
try `sudo apt install zlib1g-dev`

**Comment by TDKELL** [comment]
> try `sudo apt install zlib1g-dev`

I get the same error running make again after this. zlib1g-dev was already installed

**Comment by yair-mantis** [comment]
https://github.com/joshdoe/gst-plugins-vision/issues/55
mybe relevant

**Comment by TDKELL** [comment]
#55 is very useful however I get the same error after following the steps here:
https://github.com/joshdoe/gst-plugins-vision/issues/55#issuecomment-838909103
instead of `set(_PREFIX "/usr/lib/x86_64-linux-gnu")`  I used `set(_PREFIX "/usr/lib/aarch64-linux-gnu")`  for my system.

Unfortunately the error remains the same after performing these changes

**Comment by yair-mantis** [comment]
yes, i can replicate on WSL/ubuntu  
issue seems to stem from following commit https://github.com/joshdoe/gst-plugins-vision/commit/5925f643b1577b07d54ed10e381aa2fc87294a46

reverting the cmake directive o its old form worked for me. 
https://github.com/joshdoe/gst-plugins-vision/commit/32633b01dfd581e72746f256b277e65471d73ec8

**Comment by TDKELL** [comment]
I see that this could be causing the issue but as in https://github.com/joshdoe/gst-plugins-vision/issues/55#issuecomment-838909103  I have commented out that line (17) so that `gentl` is not made.

**Comment by 5shekel** [comment]
https://github.com/joshdoe/gst-plugins-vision/pull/68 PR

**Comment by joshdoe** [comment]
This should be fixed now.
