### ISSUE TITLE
idsueyesrc cannot detect USB3 Vision camera

### ISSUE THREAD

**Issue by ManuGira** [joshdoe/gst-plugins-vision#81]
Hi, I'm unable to use the plugin properly. I don't know if the problem comes from me or from the plugin. I hope you can help me with that.

# Issue description
In the readme it is written that USB3 Vision camera are supported by the element **idsueyesrc**. 

It works fine with my USB 2 camera **UI1007XS** from IDS.
However my USB3 Vision camera **U3-368xXLE-C** from IDS is not detected by **idsueyesrc** element (**U3-368xXLE-C** is a USB3 Vision camera from IDS).

## Steps to reproduce
1. Plug **U3-368xXLE-C** camera
2. Run command `gst-launch-1.0 idsueyesrc ! videoconvert ! autovideosink`
3. I get à segmentation fault:
```
$ gst-launch-1.0 idsueyesrc ! videoconvert ! autovideosink
Use Windows high-resolution clock, precision: 1 ms
Setting pipeline to PAUSED ...
Segmentation fault
```

## My configuration
- Windows 10
- IDS uEye version 4.95.2.0
- IDS Peak version 2.0.1.1
- gstreamer version 1.20.4
- https://github.com/joshdoe/gst-plugins-vision checked out on master (de449b5d495f65be02fb9c7871216acf12afbeca)
- USB3 Vision camera: U3-368xXLE-C
- USB 2 camera: UI1007XS

## More Info
- At first, the plugin was not working with my USB 2 camera neither, so I opened the solution in Visual Studio and commented out the line `is_ParameterSet (src->hCam, IS_PARAMETERSET_CMD_LOAD_EEPROM, NULL,
        NULL);` Then it was working fine with this USB 2 camera
- I assume gstreamer is correctly installed because this command correctly displays the testing video: 
`gst-launch-1.0 videotestsrc ! videoconvert ! autovideosink`
- I assume idsueyesrc is correctly installed because this commands correctly displays the image from my USB 2 camera:
`gst-launch-1.0 idsueyesrc ! videoconvert ! autovideosink`

**Comment by joshdoe** [comment]
Sorry for the very late response, but it looks like you have a uEye+ camera that only works with the newer IDS Peak SDK. See #86
