### ISSUE TITLE
>2 pleorasinks after tee in single pipeline won't detect/stream

### ISSUE THREAD

**Issue by jevogel** [joshdoe/gst-plugins-vision#85]
# Questions

Background information follows this section.

- Could you suggest any modifications to my pipeline which might make this work?
- Could you recommend any further debugging options to enable or steps to take?
- Could this behavior be caused by a bug in `pleorasink`?
  - If so, might it already have been fixed since 8a5478b344c0284684cc1e566332519695aedb40?

# Goal
I want to create a GStreamer pipeline that connects a single source to three GigE Vision sinks (`pleorasink`), but I haven't been able to get it to work.

# Test setup
To test the GigE Vision camera emulation, I am running the MATLAB (R2023a) Image Acquisition Explorer on my Windows 11 desktop machine ("host") connected to the MPSoC module running GStreamer on Debian ("target"). I am also using Wireshark on the host for debugging (so I can confirm whether GVCP and/or GVSP packets are being transmitted/received).

I'm using a _slightly_ modified version of `gst-plugins-vision` that was forked from commit 8a5478b344c0284684cc1e566332519695aedb40.

# What works
If I run three pipelines in parallel, I am able to detect all three cameras on the host and stream from each one. Example pipeline command:

```sh
gst-launch-1.0 videotestsrc is-live=true pattern=ball \
    ! video/x-raw,width=1000,height=1000,framerate=100/1 \
    ! pleorasink address=10.0.0.11 serial="CAM1" & \
gst-launch-1.0 videotestsrc is-live=true pattern=ball \
    ! video/x-raw,width=1000,height=1000,framerate=100/1 \
    ! pleorasink address=10.0.0.12 serial="CAM2" & \
gst-launch-1.0 videotestsrc is-live=true pattern=ball \
    ! video/x-raw,width=1000,height=1000,framerate=100/1 \
    ! pleorasink address=10.0.0.13 serial="CAM3" &
```

If I run just two `pleorasink`s in one pipeline, I am also able to detect and stream from each camera on the host. Example:

```sh
gst-launch-1.0 videotestsrc is-live=true pattern=ball \
    ! video/x-raw,width=1000,height=1000,framerate=100/1 \
    ! tee name=t \
        ! queue ! pleorasink address=10.0.0.11 serial="CAM1" \
    t.  ! queue ! pleorasink address=10.0.0.12 serial="CAM2"
```

> Note: without the `queue` elements in the above command, both cameras are detected but neither will stream frames.

It also worked to add `filesink`s after the `tee` alongside the two `pleorasink`s (that is, both cameras streamed and both video files were valid and showed the same video as the streams).

# What doesn't work

If I run three `pleorasink`s in one pipeline, I only detect two of them, and neither will stream frames. Example:

```sh
gst-launch-1.0 videotestsrc is-live=true pattern=ball \
    ! video/x-raw,width=1000,height=1000,framerate=100/1 \
    ! tee name=t \
        ! queue ! pleorasink address=10.0.0.11 serial="CAM1" \
    t.  ! queue ! pleorasink address=10.0.0.12 serial="CAM2" \
    t.  ! queue ! pleorasink address=10.0.0.13 serial="CAM3"
```

It isn't always the first two that are detected; sometimes it's the last two or the first and the third (CAM1 and CAM3).

I've also tried changing different properties on `pleorasink` and queue, none of which changes my observations:
- `pleorasink`
  - `max-lateness=150000000` (with framerate=10/1 on source)
  - `sync=false`
  - `async=false`
  - `num-internal-buffers=10`
- `queue`
  - `leaky=downstream`
  - `max-size-buffers=1`

The only thing that made _some_ difference was setting `auto-multicast=true` on `pleorasink`. That made it so all three cameras were detected on the host, but still none of them streamed frames.

Based on this and my reading, I think there is probably an issue with buffers, synchronization, or threads, but I'm not sure what to look into next.

**Comment by jevogel** [comment]
For future visitors, I was able to resolve my problem by mapping `pleorasink` instances to Ethernet interfaces using MAC addresses (with the `mac` property) instead of IP addresses. From looking at the debug log, it seems like there may have been some sort of race condition when the `pleorasink` elements were initializing and searching for the correct Ethernet interface to use.

**Comment by jevogel** [comment]
Actually, that's false. I ultimately need to create four `pleorasink` elements in one pipeline, and using the MAC addresses only worked with three of them.

**Comment by joshdoe** [comment]
@jevogel, Sorry I never got to look at this issue until now, great job explaining the situation, if only all reporters gave such detail. To be honest, I've only ever used two streams max. I've not made significant changes since the commit you mentioned, except for today I'm adding some basic attribute setting and stream channel selection to allow grabbing both streams from a dual-stream camera. It sounds like you have a workaround, but not a satisfying one, I'll close this if that's the case. Thanks!

**Comment by jevogel** [comment]
In case anyone else comes across this issue, we ended up adding a mutex to `gst_pleorasink_select_interface()` to avoid the race condition between threads when selecting interfaces and it allowed us to run four `pleorasink` elements in parallel. Unfortunately I no longer have access to the code so I can't submit a PR, but it should be straightforward to re-implement if needed.
