### ISSUE TITLE
60 or more Hz cameras

### ISSUE THREAD

**Issue by NHarishGit** [joshdoe/gst-plugins-vision#87]
This plugin is an awesome effort and usable for 30Hz cameras from various vendors. a 
a big THANK YOU to our dear @joshdoe for this commendable heavy lifting.
 
I have tried to scale and use it for 60 or more Hz camera systems and quite often than not, it errors out by saying unable to retrieve buffer etc etc.  
All things same, only sampling frequency makes it choke.
Sure, sink is not an issue in my setup, as I can run videotestsrc and filesrc all day long with 120Hz.
Thoughts ?

**Comment by joshdoe** [comment]
Happy to help. I'm not sure which specific plugin you're referring to, but I think you may be referring to `pleorasrc`. First thing to check would be to ensure you have jumbo packets enabled on your NIC, as can be verified by looking at the GStreamer debug output. You then probably want to increase the ring buffer size, `num-capture-buffers`, as it defaults to a rather low number of 3. Also, assuming you have row strides that make GStreamer happy (multiple of 4), buffers don't get copied, which means that buffer is taken out of the ring buffer until downstream elements are done with it. Usually increasing the `num-capture-buffers` helps with this too. Give it a try and let me know how it works.

**Comment by NHarishGit** [comment]
Thank you Sir @joshdoe 
I should have mentioned it before, Yes, about pleorasrc, and also I am setting packetsize=8976 and after your suggestion set the capture buffer count to 16, so far so good.
Will keep you posted
