### ISSUE TITLE
OpenCV Gstreamer Plugin Windows 10

### ISSUE THREAD

**Issue by NHarishGit** [joshdoe/gst-plugins-vision#9]
Josh

is there a way that I can call your plugins from OpenCV (I have rebuilt OpenCV 4.1.2 libs with Gstreamer support) Windows Application using VS C++ 2017 (compiler) ?

Basically, I am trying to make a c++ application, which will use your plugin to talk to a GigE Pleora camera, get the video into OpenCV for image enhancement and then display it using OpenCV imshow functions.

your thoughts ?

Thanks and Regards
Nitin

**Comment by joshdoe** [comment]
Sure, I've done that. If you've built OpenCV with GStreamer support, then
just set GST_PLUGIN_PATH to the directory containing the Pleora plugin, and
call VideoReader with a GStreamer pipeline. What pixel format are you
using? If GRAY16_LE/BE, there's an OpenCV patch to add that support. I can
link to it next time I'm at a PC.

**Comment by NHarishGit** [comment]
Josh

I tried to build a very simple App and GStreamer Pipeline using the Plugin doesn't seem to work.

here is a screen shot:
<img width="1920" alt="GStreamerOpenCVError" src="https://user-images.githubusercontent.com/57957650/69650532-be98f980-103c-11ea-8575-33f8afd20d7b.png">

**Comment by joshdoe** [comment]
Your pipeline in your main function should have appsink, not autovideosink, per the warning in the command prompt. I don't see an error for libgstpleora.dll, so I assume the Pleora plugin itself is working. Actually, before trying pleorasrc try videotestsrc.

**Comment by NHarishGit** [comment]
Thank you for your prompt reply.
But using VideoTstSrc with APPSINK also throws an error, see below:

<img width="1920" alt="GStreamerOpenCVErrorWithVideoTstSrcAPPSINK" src="https://user-images.githubusercontent.com/57957650/69672612-6d056480-1066-11ea-9f2e-692b468e3e78.png">

**Comment by NHarishGit** [comment]
@joshdoe, Sorry, I went into some other projects and now I am back on this one.

Now, I have:

**Windows 10 PRO
OpenCV 4.2.0
GStreamer 1.16.2
GST Plugin build from your master
CUDA 10.2
VS 2019 Community**

I do see that my old code after few upgrades can run "cv::VideoCapture cap("videotestsrc ! autovideoconvert ! appsink", cv::CAP_GSTREAMER);", see the following output:

<img width="793" alt="VideoTestSrc" src="https://user-images.githubusercontent.com/57957650/73781187-d3d98500-475d-11ea-835f-cfbc1302678c.PNG">


But, still "cv::VideoCapture cap("pleorasrc ! autovideoconvert ! appsink", cv::CAP_GSTREAMER);" gives me an error, see below:
<img width="1341" alt="PleoraSrc" src="https://user-images.githubusercontent.com/57957650/73781346-10a57c00-475e-11ea-8a8e-7499688cc446.PNG">

Thoughts ?

Thanks and Regards
Nitin

**Comment by joshdoe** [comment]
What version of Pleora are you using? From the looks of it you have both my
binary release and the build you made, with all those spurious plugins not
being loaded due to missing dependencies. I'd remove those to reduce
clutter. There's not enough info in those logs. Run with
GST_DEBUG=*:3,pleora*:6 to get more verbose error messages. What pixel
format is your camera using? It works with gst-launch directly? Give the
caps shown with the -v option.

**Comment by NHarishGit** [comment]
I have pleora v 6
I will try tour suggestions tomorrow as I already left from work.

Thanks and kindly stay tuned

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joshdoe** [comment]
I'm closing this issue as I believe your problem has been fixed.
